### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by kraemer-raimund** [ertanturan/Unity-Localization#1]
Judging by how the Readme file is written, it seems like this repository was intended as an open source project. I did however not find a license in this repository, which means that nobody can legally use the code without explicit permission by the author (with few exceptions determined by the GitHub Terms of Service).

If you intended to make this project open source, you might want to consider adding a license, or making it more visible if it exists somewhere already.

Here is more information about it from GitHub:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

A related question on StackExchange:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by ertanturan** [comment]
Thanks a lot for the heads up !. I've changed the license to the repository !
